<!--#include file="inc/inc_sys.asp"-->
<%
if session("rank")>2 then
conn.close
set conn = nothing
response.Write "<script language='javascript'>alert('你无权添加修改文章资料！');history.go(-1);</script>"
response.End
end if

dim action,articleid,temp,strContent,i,strarticlecontent
articleid=SafeRequest("id",1)
action=FormatSQL(SafeRequest("action",0))
select case action
case "add"
set rs=server.CreateObject("adodb.recordset")
rs.Open "select * from sdx_article",conn,1,3
rs.AddNew
rs("articletitle")=trim(request.form("articletitle")) 
rs("articleintroduce")=trim(request.form("articleintroduce")) 
rs("addname")=trim(request.form("addname")) 
rs("articlefrom")=trim(request.form("articlefrom")) 
rs("articlepic")=trim(request.form("articlepic")) 
rs("artbclassid")=trim(request.form("artbclassid")) 
rs("artsclassid")=trim(request.form("artsclassid")) 
rs("bclassid")=trim(request.form("bclassid")) 
rs("sclassid")=trim(request.form("sclassid"))  
rs("artfeatureName")=trim(request.form("artfeatureName"))  
rs("arttop")=trim(request.form("arttop")) 
rs("artrec")=trim(request.form("artrec")) 
rs("arthot")=trim(request.form("arthot")) 
rs("lang")=trim(request.form("lang"))
rs("adddate")=Now() 
rs("viewnum")=0 
For i = 1 To Request.Form("articlecontent").Count 
strarticlecontent = strarticlecontent & Request.Form("articlecontent")(i) 
Next 
rs("articlecontent")=strarticlecontent
rs.Update
rs.close
set rs=nothing
conn.close
set conn=nothing
response.Write "<script language=javascript>alert('添加成功！');history.go(-1);</script>"
response.End

case "edit"
set rs=server.CreateObject("adodb.recordset")
rs.Open "select * from sdx_article where articleid="&articleid,conn,1,3
rs("articletitle")=trim(request.form("articletitle")) 
rs("articleintroduce")=trim(request.form("articleintroduce")) 
rs("addname")=trim(request.form("addname")) 
rs("articlefrom")=trim(request.form("articlefrom")) 
rs("articlepic")=trim(request.form("articlepic")) 
rs("artbclassid")=trim(request.form("artbclassid")) 
rs("artsclassid")=trim(request.form("artsclassid")) 
rs("bclassid")=trim(request.form("bclassid")) 
rs("sclassid")=trim(request.form("sclassid"))  
rs("artfeatureName")=trim(request.form("artfeatureName"))  
rs("arttop")=trim(request.form("arttop")) 
rs("artrec")=trim(request.form("artrec")) 
rs("arthot")=trim(request.form("arthot"))
rs("lang")=trim(request.form("lang")) 
rs("viewnum")=0 
For i = 1 To Request.Form("articlecontent").Count 
strarticlecontent = strarticlecontent & Request.Form("articlecontent")(i) 
Next 
rs("articlecontent")=strarticlecontent
rs.Update
rs.Close
set rs=nothing
conn.close
set conn=nothing
response.Write "<script language=javascript>alert('修改成功！');history.go(-1);</script>"
response.End
end select
%>
